#version: '3.8'

services:
  # Laravel application container
  app:
    build:
      context: .
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    ports:
      - "8000:9000"  # Map port 8000 on host to port 9000 inside the container

  # MySQL container
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel_network

  # Nginx container (optional, for serving Laravel)
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www
    ports:
      - "8080:80"  # Map port 8080 on host to port 80 inside the container
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql-data:
